---
- name: Install apache httpd
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Ensure apache2 is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- name: Copy index.html to web root
  copy:
    src: files/index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
